In [1]:
import numpy as np

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
b= np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [25]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [26]:
a @ b

array([[6., 6.],
       [6., 6.]])

In [28]:
import requests
from bs4 import BeautifulSoup as bs

Load our first Page

In [29]:
r = requests.get("https://keithgalli.github.io/web-scraping/example.html")

In [33]:
# Convert to Beautifulsoup obj
soup = bs(r.content)
print(soup.prettify())

<html>
 <head>
  <title>
   HTML Example
  </title>
 </head>
 <body>
  <div align="middle">
   <h1>
    HTML Webpage
   </h1>
   <p>
    Link to more interesting example:
    <a href="https://keithgalli.github.io/web-scraping/webpage.html">
     keithgalli.github.io/web-scraping/webpage.html
    </a>
   </p>
  </div>
  <h2>
   A Header
  </h2>
  <p>
   <i>
    Some italicized text
   </i>
  </p>
  <h2>
   Another header
  </h2>
  <p id="paragraph-id">
   <b>
    Some bold text
   </b>
  </p>
 </body>
</html>



### Start soup scraping

In [34]:
# find and find_all
first_header = soup.find('h2') # It will find only first value that it gets and return tthe op.
first_header

<h2>A Header</h2>

In [35]:
header = soup.find_all('h2') # It wiill find all the header in the txt file/html
header

[<h2>A Header</h2>, <h2>Another header</h2>]

In [36]:
first_header = soup.find(['h2','h1']) #Hence it will find any element that came first. Order doesnt matter.
first_header

<h1>HTML Webpage</h1>

In [37]:
header = soup.find_all(['h2','h1'])
header

[<h1>HTML Webpage</h1>, <h2>A Header</h2>, <h2>Another header</h2>]

In [39]:
paragraph  = soup.find_all('p',attrs={'id':'paragraph-id'})
paragraph

[<p id="paragraph-id"><b>Some bold text</b></p>]

### You can nest find/find_all function

In [42]:
body = soup.find('body')
div = body.find('div')
header = div.find('h1')
header

<h1>HTML Webpage</h1>

In [50]:
import re

In [54]:
# We can search specific string in find/find_all function
paragraph = soup.find_all("p",string=re.compile("Some"))
paragraph

[<p><i>Some italicized text</i></p>,
 <p id="paragraph-id"><b>Some bold text</b></p>]

### Use of select statement

In [56]:
content = soup.select('div p') # Here, we are selecting the div and inside div we have p tag
content

[<p>Link to more interesting example: <a href="https://keithgalli.github.io/web-scraping/webpage.html">keithgalli.github.io/web-scraping/webpage.html</a></p>]

In [57]:
# Select all the p tags that were preceeded with h tag (after h tag)
paragraphs = soup.select('h2 ~ p')
paragraphs

[<p><i>Some italicized text</i></p>,
 <p id="paragraph-id"><b>Some bold text</b></p>]

In [58]:
import pandas as pd

In [60]:
pokemon_df = pd.read_csv('pokemon_data.csv')
pokemon_df.head(8)

#                       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1                  Bulbasaur  Grass  Poison  45      49       49       65   
1  2                    Ivysaur  Grass  Poison  60      62       63       80   
2  3                   Venusaur  Grass  Poison  80      82       83      100   
3  3      VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4  4                 Charmander   Fire     NaN  39      52       43       60   
5  5                 Charmeleon   Fire     NaN  58      64       58       80   
6  6                  Charizard   Fire  Flying  78      84       78      109   
7  6  CharizardMega Charizard X   Fire  Dragon  78     130      111      130   

   Sp. Def  Speed  Generation  Legendary  
0       65     45           1      False  
1       80     60           1      False  
2      100     80           1      False  
3      120     80           1      False  
4       50     65           1      False  
5       65     80           1      False  
6       85    100           1      False  
7       85    100           1      False

In [61]:
print('Hello')

Hello
